import { Destination } from "./DestinationCard";

export const destinations: Destination[] = [
  { name: "Dubai", img: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80", cat: "city", catIcon: "location_city", tags: ["City", "Luxury", "Desert"], region: "UAE · Middle East", desc: "The city of gold — iconic skylines, desert safaris, and world-class luxury await in this dazzling metropolis.", season: "Year-round", packages: "48 packages", rating: "4.9", reviews: "312", price: 124999, priceLabel: "₹1,24,999" },
  { name: "Maldives", img: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=600&q=80", cat: "beach", catIcon: "beach_access", tags: ["Beach", "Nature", "Tropical", "Luxury"], region: "Maldives · South Asia", desc: "A tropical paradise with pristine beaches, crystal-clear lagoons, and overwater bungalows like nowhere else on earth.", season: "Nov – Apr", packages: "31 packages", rating: "5.0", reviews: "209", price: 69999, priceLabel: "₹69,999" },
  { name: "Bali", img: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80", cat: "tropical", catIcon: "sunny", tags: ["Tropical", "Beach", "Nature", "Cultural"], region: "Bali · Indonesia", desc: "An enchanting island offering stunning beaches, vibrant culture, lush rice terraces, and world-class wellness retreats.", season: "Apr – Oct", packages: "52 packages", rating: "4.9", reviews: "524", price: 44999, priceLabel: "₹44,999" },
  { name: "Japan", img: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80", cat: "cultural", catIcon: "museum", tags: ["Cultural", "Heritage", "Nature", "City"], region: "Japan · East Asia", desc: "Ancient temples, neon-lit cities, cherry blossoms, and bullet trains — Japan is a seamless blend of old and new.", season: "Mar – May", packages: "29 packages", rating: "4.9", reviews: "178", price: 114999, priceLabel: "₹1,14,999" },
  { name: "Singapore", img: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=600&q=80", cat: "city", catIcon: "location_city", tags: ["City", "Nature", "Family"], region: "Singapore · SE Asia", desc: "A futuristic city-state where gleaming skyscrapers meet lush gardens, world-class food, and vibrant culture.", season: "Year-round", packages: "36 packages", rating: "4.8", reviews: "401", price: 72999, priceLabel: "₹72,999" },
  { name: "Thailand", img: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&q=80", cat: "beach", catIcon: "beach_access", tags: ["Beach", "Heritage", "Tropical", "Nature"], region: "Thailand · SE Asia", desc: "Turquoise waters, golden temples, vibrant street food, and island-hopping adventures across Phuket and Koh Samui.", season: "Nov – Apr", packages: "44 packages", rating: "4.8", reviews: "374", price: 39999, priceLabel: "₹39,999" },
  { name: "Paris", img: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80", cat: "cultural", catIcon: "museum", tags: ["Cultural", "Heritage", "City"], region: "France · Europe", desc: "The City of Light — iconic landmarks, world-class cuisine, romantic boulevards, and timeless art at every corner.", season: "Apr – Jun", packages: "22 packages", rating: "4.8", reviews: "289", price: 149999, priceLabel: "₹1,49,999" },
  { name: "Santorini", img: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=600&q=80", cat: "beach", catIcon: "beach_access", tags: ["Beach", "Heritage", "Tropical"], region: "Greece · Europe", desc: "Whitewashed cliffside villages, volcanic beaches, and legendary sunsets over the Aegean Sea.", season: "May – Oct", packages: "18 packages", rating: "4.9", reviews: "156", price: 149999, priceLabel: "₹1,49,999" },
  { name: "Nepal", img: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80", cat: "adventure", catIcon: "hiking", tags: ["Adventure", "Mountain", "Pilgrimage", "Heritage", "Nature"], region: "Nepal · South Asia", desc: "Home to the world’s highest peaks — trek through the Himalayas, explore ancient temples, and experience raw adventure.", season: "Oct – May", packages: "16 packages", rating: "4.7", reviews: "134", price: 89999, priceLabel: "₹89,999" },
  { name: "Kenya Safari", img: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600&q=80", cat: "wildlife", catIcon: "forest", tags: ["Wildlife", "Nature", "Adventure"], region: "Kenya · Africa", desc: "Witness the Great Migration, spot the Big Five, and sleep under the stars in the Maasai Mara — Africa’s crown jewel.", season: "Jul – Oct", packages: "12 packages", rating: "4.8", reviews: "98", price: 199999, priceLabel: "₹1,99,999" },
  { name: "Kashmir", img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80", cat: "mountain", catIcon: "landscape", tags: ["Mountain", "Nature", "Heritage"], region: "Kashmir · India", desc: "Paradise on earth — snow-capped peaks, shikara rides on Dal Lake, saffron fields, and Mughal gardens in full bloom.", season: "Apr – Oct", packages: "24 packages", rating: "4.7", reviews: "211", price: 54999, priceLabel: "₹54,999" },
  { name: "New York", img: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600&q=80", cat: "city", catIcon: "location_city", tags: ["City", "Cultural"], region: "New York · USA", desc: "The city that never sleeps — Times Square, Central Park, world-class museums, and the iconic Manhattan skyline.", season: "Sep – Nov", packages: "15 packages", rating: "4.8", reviews: "167", price: 179999, priceLabel: "₹1,79,999" },
];
